services:
  - type: web
    name: high-adventure-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: high-adventure-db
          property: connectionString
    healthCheckPath: /
    
databases:
  - name: high-adventure-db
    plan: free 